### ISSUE TITLE
gdrive.auth.service が None になる事象を解決する

### ISSUE THREAD

**Issue by ftnext** [ftnext/diy-googledrive-operate#6]
#4 で invalid_grant エラーを解消した後に発生

```
$ python main.py 1******************************************o --d specified_title_test
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 12, in main
    dest_file = cp_in_drive(args.source_id, args.dest_title)
  File "main.py", line 32, in cp_in_drive
    return drive.copy_file(source_id, dest_title)
  File "/.../diy-googledrive-operate/operate_drive/drive.py", line 19, in copy_file
    access_to_files = self._drive.auth.service.files()
AttributeError: 'NoneType' object has no attribute 'files'
```

**Comment by ftnext** [comment]
## 再現確認

```python
>>> from operate_drive import create_diy_gdrive
>>> gdrive = create_diy_gdrive()
>>> gdrive._drive
<pydrive2.drive.GoogleDrive object at 0x10277f5e0>
>>> gdrive._drive.auth
<pydrive2.auth.GoogleAuth object at 0x1028d63d0>
>>> gdrive._drive.auth.service
>>> gdrive._drive.auth.service.files()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'files'
```

Workaround: drive.pyのソースに見つけた `GetAbout()`を呼ぶとNoneでなくなった
（裏で通信が走ったためと考えている）

```python
>>> info = gdrive._drive.GetAbout()
>>> info = gdrive._drive.auth
>>> gdrive._drive.auth
<pydrive2.auth.GoogleAuth object at 0x1028d63d0>
>>> gdrive._drive.auth.service
<googleapiclient.discovery.Resource object at 0x1042c3ca0>
```

**Comment by ftnext** [comment]
## PyDriveのバージョンアップを試す → 解決せず

`file.GetContentFile` で同様のエラーが発生していたというIssueを見つけた
https://github.com/iterative/PyDrive2/issues/31

- バージョンアップ前: `PyDrive2==1.4.10` ref: requirements.lock
- バージョンアップ後: `PyDrive2==1.8.1`

解決しなかった（エラーが再現した）ので、バージョンは元に戻した

**Comment by ftnext** [comment]
GetAbout のドキュメント
https://iterative.github.io/PyDrive2/docs/build/html/pydrive2.html#pydrive2.drive.GoogleDrive.GetAbout
